---
- name: Install php5-fpm
  apt: name={{ item }} state=present
  with_items:
    - php5-fpm
    - php5-mysql
    - php5-common
    - libapache2-mod-php5

- name: Copy custom www.conf file with the Change in permission of php5-fpm.sock
  copy: src=www.conf dest=/etc/php5/fpm/pool.d backup=yes
  notify:
     - Restart PHP5-FPM

- name: Copy custom php.ini file(cgi.fix_pathinfo=0) 
  copy: src=php.ini dest=/etc/php5/fpm backup=yes
  notify:
     - Restart PHP5-FPM 

